Repository codestates-seb/seb44_main_020, pull requests merged in 2023-07, with the labels that each got.

#42 Feat/minwoo/member
  server/src/main/java/moovda_project/moovda/member/entity/Member.java
Labels: Feature

#36 [feat] Movie, Comment, Like 엔티티 작성
  server/src/main/java/com/moovda_project/moovda/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/like/entity/like.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Watched.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/Genre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/MovieStaff.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/Staff.java
Labels: Feature

#38 [feat] : dto 추가,의존성 추가
  .idea/modules/moovda_project.moovda.main.iml
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/answer/entity/Answer.java
  server/src/main/java/com/moovda_project/moovda/audit/Auditable.java
  server/src/main/java/com/moovda_project/moovda/dto/PageInfo.java
  server/src/main/java/com/moovda_project/moovda/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/question/entity/Question.java
  server/src/main/java/com/moovda_project/moovda/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/question/repository/QuestionRepository.java
  server/src/main/java/com/moovda_project/moovda/question/service/QuestionService.java
Labels: Feature

#43 [fix] Member 경로 수정
  server/src/main/java/com/moovda_project/moovda/member/entity/Member.java
Labels: Fix

#53 [feat] Question CRUD
  server/src/main/java/com/moovda_project/moovda/exception/BusinessLogicException.java
  server/src/main/java/com/moovda_project/moovda/exception/ExceptionCode.java
  server/src/main/java/com/moovda_project/moovda/question/controller/QuestionController.java
  server/src/main/java/com/moovda_project/moovda/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/question/repository/QuestionRepository.java
  server/src/main/java/com/moovda_project/moovda/question/service/QuestionService.java
  server/src/main/java/com/moovda_project/moovda/utils/UriCreator.java
Labels: Feature

#54 Feat/minwoo/jwtoauth
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/jwt/JwtTokenizer.java
  server/src/main/resources/application.yml
Labels: Feature

#55 [feat] ApiController, Service 작성
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/movie/controller/ApiController.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/MovieRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/service/ApiService.java
Labels: Feature

#59 [fix] 버그 수정
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/MoovdaApplication.java
  server/src/main/java/com/moovda_project/moovda/answer/entity/Answer.java
  server/src/main/java/com/moovda_project/moovda/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/jwt/JwtTokenizer.java
  server/src/main/java/com/moovda_project/moovda/question/controller/QuestionController.java
  server/src/main/java/com/moovda_project/moovda/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/question/entity/Question.java
  server/src/main/java/com/moovda_project/moovda/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/question/service/QuestionService.java
Labels: Bug

#61 [feat] Genre. Staff DB 저장 구현
  server/src/main/java/com/moovda_project/moovda/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/Genre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/GenreRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/MovieStaff.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/Staff.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/StaffRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/service/ApiService.java
Labels: Feature

#64 [feat] Comment 관련 기능 구현
  server/src/main/java/com/moovda_project/moovda/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/comment/repository/CommentRepository.java
  server/src/main/java/com/moovda_project/moovda/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/exception/ExceptionCode.java
  server/src/main/java/com/moovda_project/moovda/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Watched.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/ToWatchRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/WatchedRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/movie/service/WatchedService.java
Labels: Feature

#67 [refactor] @PostConstruct 추가
  server/src/main/java/com/moovda_project/moovda/movie/controller/ApiController.java
Labels: Refactor

#70 [refactor] 연관관계 매핑 수정
  server/src/main/java/com/moovda_project/moovda/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/Watched.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/MovieStaff.java
Labels: Refactor

#69 [feat] webeditor
  client/package-lock.json
  client/package.json
  client/src/components/Question/Webeditor.tsx
Labels: Feature

#74 [feat] 질문 조회 기능 구현
  server/src/main/java/com/moovda_project/moovda/question/controller/QuestionController.java
  server/src/main/java/com/moovda_project/moovda/question/dto/MultiResponseDto.java
  server/src/main/java/com/moovda_project/moovda/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/question/entity/Question.java
  server/src/main/java/com/moovda_project/moovda/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/question/service/QuestionService.java
Labels: Feature, Fix

#75 [feat] JWT Oauth2 구현
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/member/repository/MemberRepository.java
  server/src/main/java/com/moovda_project/moovda/member/service/MemberService.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/config/SecurityConfiguration.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/filter/JwtVerificationFilter.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/jwt/JwtTokenizer.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/jwttest/JwtTokenizerTest.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/utils/ErrorResponder.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/utils/MemberIdExtractor.java
  server/src/main/java/com/moovda_project/moovda/response/ErrorResponse.java
  server/src/main/java/com/moovda_project/moovda/utils/CustomAuthorityUtils.java
  server/src/main/resources/application.yml
Labels: Feature

#76 [feat] jwt oauth 수정
  server/src/main/java/com/moovda_project/moovda/utils/CustomAuthorityUtils.java
Labels: Fix

#77 [feat] Comment 기능 추가
  server/src/main/java/com/moovda_project/moovda/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/comment/dto/CommentPatchDto.java
  server/src/main/java/com/moovda_project/moovda/comment/dto/CommentPostDto.java
  server/src/main/java/com/moovda_project/moovda/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/exception/ExceptionCode.java
Labels: Feature, Refactor

#85 [feat] jwt 자체로그인 구현
  server/src/main/java/com/moovda_project/moovda/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/member/dto/MemberDto.java
  server/src/main/java/com/moovda_project/moovda/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/member/repository/MemberRepository.java
  server/src/main/java/com/moovda_project/moovda/member/service/MemberService.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/config/SecurityConfiguration.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/config/SecurityConfigurationV2.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/userdetails/JwtAuthenticationFilter.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/userdetails/LoginDto.java
  server/src/main/java/com/moovda_project/moovda/oauth2_jwt/userdetails/MemberDetailsService.java
  server/src/main/java/com/moovda_project/moovda/question/mapper/QuestionMapper.java
  server/src/main/resources/application.yml
Labels: Feature

#82 [feat] QuestionBox 컴포넌트
  client/src/components/Question/QuestionBox.styled.ts
  client/src/components/Question/QuestionBox.tsx
Labels: Feature

#81 [feat] Answer CRUD 기능 추가
  server/src/main/java/com/moovda_project/moovda/answer/controller/AnswerController.java
  server/src/main/java/com/moovda_project/moovda/answer/dto/AnswerDto.java
  server/src/main/java/com/moovda_project/moovda/answer/entity/Answer.java
  server/src/main/java/com/moovda_project/moovda/answer/mapper/AnswerMapper.java
  server/src/main/java/com/moovda_project/moovda/answer/repository/AnswerRepository.java
  server/src/main/java/com/moovda_project/moovda/answer/service/AnswerService.java
Labels: Feature, Fix

#84 [refactor] Movie 도메인 리팩토링
  server/src/main/java/com/moovda_project/moovda/movie/api/ApiService.java
  server/src/main/java/com/moovda_project/moovda/movie/api/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/Genre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/genre/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/MovieStaff.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/staff/Staff.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/watch/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/movie/entity/watch/Watched.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/genre/GenreRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/staff/StaffRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/watch/ToWatchRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/repository/watch/WatchedRepository.java
  server/src/main/java/com/moovda_project/moovda/movie/service/watch/WatchedService.java
Labels: Refactor

#83 [feat] Like 기능 추가
  server/src/main/java/com/moovda_project/moovda/comment/controller/LikeController.java
  server/src/main/java/com/moovda_project/moovda/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/comment/entity/Like.java
  server/src/main/java/com/moovda_project/moovda/comment/repository/LikeRepository.java
  server/src/main/java/com/moovda_project/moovda/comment/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/like/entity/like.java
Labels: Feature, Refactor

#87 [fix] Answer Service 수정
  server/src/main/java/com/moovda_project/moovda/answer/service/AnswerService.java
Labels: Fix

#88 [fix] Answer Dto 수정
  server/src/main/java/com/moovda_project/moovda/answer/dto/AnswerDto.java
Labels: Fix

#91 [rename] auth로 패키지 이름 변경
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfigurationV2.java
  server/src/main/java/com/moovda_project/moovda/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/moovda_project/moovda/global/auth/jwttest/JwtTokenizerTest.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/JwtAuthenticationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/LoginDto.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/moovda_project/moovda/global/auth/utils/ErrorResponder.java
  server/src/main/java/com/moovda_project/moovda/global/auth/utils/MemberIdExtractor.java
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/LikeController.java
Labels: Refactor

#92 [comment] build.gradle 주석 제거
  server/build.gradle
Labels: Refactor

#96 [fix] Security jwt 검증 관련 에러 해결
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfigurationV2.java
  server/src/main/java/com/moovda_project/moovda/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/JwtAuthenticationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/utils/MemberIdExtractor.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
Labels: Fix

#93 [feat] question box 기능 추가
  client/src/components/Question/QuestionBox.styled.ts
  client/src/components/Question/QuestionBox.tsx
  client/src/styles/Globalstyle.tsx
Labels: Feature

#94 [feat] webeditor placeholder 제거
  client/src/components/Question/Webeditor.tsx
Labels: Feature

#95 [feat]/soobin/auth2
  client/package-lock.json
  client/package.json
  client/src/app/(membership)/login/page.styled.ts
  client/src/app/(membership)/login/page.tsx
  client/src/app/_app.tsx
  client/src/app/api/auth/[...nextauth]/route.ts
  client/src/app/layout.tsx
  client/src/assets/GoogleLogo.svg
  client/src/assets/LoginLogo.svg
  client/src/components/Header/Header.tsx
  client/src/redux/features/authSlice.ts
  client/src/redux/store.ts
  client/src/styles/style.tsx
Labels: Feature

#100 [refactor] Comment 리팩토링
  server/src/main/java/com/moovda_project/moovda/global/exception/ExceptionCode.java
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPatchDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPostDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/module/comment/repository/CommentRepository.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/Movie.java
Labels: Refactor, Fix

#105 [Design] question box 디자인 수정
  client/src/components/Question/QuestionBox.styled.ts
  client/src/components/Question/QuestionBox.tsx
Labels: Fix

#106 [feat] 코멘트 좋아요 추가
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/LikeController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/Movie.java
Labels: Feature, Fix

#103 [feat] answer box
  client/src/components/Question/AnswerBox.styled.ts
  client/src/components/Question/AnswerBox.tsx
Labels: Feature

#107 [Feat] search modal 틀 구현
  client/src/components/Question/Modal.styled.ts
  client/src/components/Question/Modal.tsx
Labels: Feature

#110 [feat] 영화 상세 조회 추가
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/GenreResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/StaffResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/genre/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
Labels: Feature

#111 [feat] SingleResponseDto 추가
  server/src/main/java/com/moovda_project/moovda/global/dto/SingleResponseDto.java
Labels: Feature

#113 [feat] 볼 영화 기능 구현
  server/src/main/java/com/moovda_project/moovda/global/exception/ExceptionCode.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/ToWatchController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/watch/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/watch/ToWatchService.java
Labels: Feature

#115 [feat] Question 본인 인증 기능 추가
  server/src/main/java/com/moovda_project/moovda/global/dto/PageInfo.java
  server/src/main/java/com/moovda_project/moovda/module/member/service/MemberService.java
  server/src/main/java/com/moovda_project/moovda/module/question/controller/QuestionController.java
  server/src/main/java/com/moovda_project/moovda/module/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/module/question/entity/Question.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/module/question/service/QuestionService.java
Labels: Feature

#117 [feat] 영화 필터 기능 추가
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/global/dto/MultiResponseDto.java
  server/src/main/java/com/moovda_project/moovda/global/dto/PageInfo.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieSearchDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepository.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryCustom.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/watch/ToWatchRepository.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/module/search/MovieSearchCondition.java
Labels: Feature, Refactor

#108 [Feat] question create page
  client/package-lock.json
  client/package.json
  client/src/app/questions/create/page.styled.ts
  client/src/app/questions/create/page.tsx
  client/src/assets/questionsvg.svg
Labels: Feature

#118 [refactor] 영화, 코멘트 기능 수정
  server/src/main/java/com/moovda_project/moovda/global/exception/ExceptionCode.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/ToWatchController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/watch/ToWatchService.java
Labels: Feature, Refactor

#119 Feat/minwoo/gradle
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieDataInitializer.java
  server/src/main/resources/application.yml
Labels: Fix

#121 [chore] 환경변수 및 DB 설정
  server/build.gradle
  server/src/main/resources/application.yml
Labels: Refactor

#123 [fix] config 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfigurationV2.java
Labels: Fix

#120 [feat] Answer 작성자 확인 메서드 추가
  server/src/main/java/com/moovda_project/moovda/module/answer/controller/AnswerController.java
  server/src/main/java/com/moovda_project/moovda/module/answer/dto/AnswerDto.java
  server/src/main/java/com/moovda_project/moovda/module/answer/mapper/AnswerMapper.java
  server/src/main/java/com/moovda_project/moovda/module/answer/service/AnswerService.java
Labels: Feature

#146 [docs] 파이프라인 세팅
  server/appspec.yml
  server/buildspec.yml
  server/scripts/initialize.sh
  server/scripts/server_clear.sh
  server/scripts/server_start.sh
  server/scripts/server_stop.sh
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfigurationV2.java
Labels: Refactor, Deployment

#147 [docs] buildspec.yml 수정
  server/buildspec.yml
Labels: Deployment

#148 [fix] pipeline 에러 수정을 위한 삭제
  server/appspec.yml
  server/buildspec.yml
  server/scripts/initialize.sh
  server/scripts/server_clear.sh
  server/scripts/server_start.sh
  server/scripts/server_stop.sh
Labels: Fix

#149 [docs] yml 수정
  server/src/main/resources/application.yml
Labels: Fix

#153 [fix] Security 에러 수정
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/MoovdaApplication.java
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfigurationV2.java
  server/src/main/java/com/moovda_project/moovda/global/auth/dto/LoginDto.java
  server/src/main/java/com/moovda_project/moovda/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/moovda_project/moovda/global/auth/jwttest/JwtTokenizerTest.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/moovda_project/moovda/global/utils/CustomAuthorityUtils.java
  server/src/main/java/com/moovda_project/moovda/global/utils/ErrorResponder.java
  server/src/main/java/com/moovda_project/moovda/global/utils/MemberIdExtractor.java
  server/src/main/java/com/moovda_project/moovda/module/answer/controller/AnswerController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/LikeController.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/ToWatchController.java
  server/src/main/java/com/moovda_project/moovda/module/question/controller/QuestionController.java
Labels: Refactor, Fix

#154 [refactor] 리팩토링
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPostDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/module/like/controller/LikeController.java
  server/src/main/java/com/moovda_project/moovda/module/like/entity/Like.java
  server/src/main/java/com/moovda_project/moovda/module/like/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/member/repository/MemberRepository.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieApiService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/genre/GenreResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/staff/StaffResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryCustom.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
  server/src/main/java/com/moovda_project/moovda/module/watch/controller/ToWatchController.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/Watched.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/WatchedService.java
Labels: Refactor

#155 [refactor] 패키지 구조 수정 및 리팩토링
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/like/repository/LikeRepository.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/module/watch/repository/ToWatchRepository.java
  server/src/main/java/com/moovda_project/moovda/module/watch/repository/WatchedRepository.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/ToWatchService.java
Labels: Refactor

#157 [fea] GlobalExceptionAdvice 추가
  server/src/main/java/com/moovda_project/moovda/global/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/moovda_project/moovda/global/response/ErrorResponse.java
Labels: Feature

#161 [feat] 멤버 상세 조회 추가
  server/src/main/java/com/moovda_project/moovda/module/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/like/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/member/service/MemberService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/watch/dto/ToWatchResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/watch/dto/WatchedResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/ToWatchService.java
Labels: Feature, Refactor

#162 [feat] 페이지네이션 추가
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPatchDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/module/like/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDtoV2.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/PageDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
Labels: Feature, Refactor

#163 [chore] build.gradle 서버 세팅
  server/build.gradle
Labels: Deployment

#164 [chore] build.gradle 서버 세팅
  server/build.gradle
Labels: Deployment

#165 [chore] build.gradle 서버 세팅
  server/build.gradle
Labels: Deployment

#166 [fix] SpringCloud 에러 수정
  server/src/main/resources/application.yml
Labels: Fix, Deployment

#167 [fix] SpringCloud 에러 수정
  server/build.gradle
  server/src/main/resources/application.yml
  server/src/main/resources/bootstrap.yml
Labels: Fix, Deployment

#168 [fix] SpringCloud 에러 수정
  server/src/main/resources/application.yml
  server/src/main/resources/bootstrap.yml
Labels: Refactor, Fix

#169 [fix] SpringCloud 에러 수정
  server/src/main/resources/application.yml
Labels: Fix

#170 [fix] SpringCloud 에러 수정
  server/build.gradle
Labels: Fix

#171 [fix] SpringCloud 에러 수정
  server/src/main/resources/application.yml
Labels: Fix

#172 [fix] SpringCloud 에러 수정
  server/build.gradle
  server/src/main/resources/application.yml
Labels: Fix

#173 [fix] SpringCloud 에러 수정
  server/build.gradle
  server/src/main/resources/application.yml
  server/src/main/resources/bootstrap.yml
Labels: Fix

#174 [fix] SpringCloud 에러 수정
  server/src/main/resources/application.yml
Labels: Fix

#175 [fix] transaction 에러 수정
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieApiService.java
Labels: Fix

#177 [refactor] 코멘트, 좋아요, 영화 리팩토링
  server/build.gradle
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPostDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/like/controller/LikeController.java
  server/src/main/java/com/moovda_project/moovda/module/like/entity/Like.java
  server/src/main/java/com/moovda_project/moovda/module/like/repository/LikeRepository.java
  server/src/main/java/com/moovda_project/moovda/module/like/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieApiService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieSearchDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/genre/Genre.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/staff/MovieStaff.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/Watched.java
Labels: Refactor

#178 [refactor] Movie, Watch 리팩토링
  server/src/main/java/com/moovda_project/moovda/global/dto/PageDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieApiService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/PagedMovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/search/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/search/MovieSearchDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryCustom.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/module/watch/repository/ToWatchRepository.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/ToWatchService.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/WatchedService.java
Labels: Refactor

#180 [chore] build.gradle 수정
  server/build.gradle
Labels: Fix

#183 [refactor] 페이지네이션 관련 수정
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
Labels: Refactor

#184 [refactor] 코멘트 좋아요 수 내림차순 추가
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
Labels: Feature

#185 [feat] 메인 화면 기능 추가
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieMainResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
Labels: Feature

#186 [refactor] Question Refactoring
  server/src/main/java/com/moovda_project/moovda/module/question/controller/QuestionController.java
  server/src/main/java/com/moovda_project/moovda/module/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/module/question/entity/Question.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/module/question/service/QuestionService.java
Labels: Refactor

#187 [refactor] QuestionDto Refactoring
  server/src/main/java/com/moovda_project/moovda/module/question/dto/QuestionDto.java
Labels: Refactor

#190 [feat] 마이 페이지 본 영화 별점 추가
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/watch/dto/WatchedResponseDto.java
Labels: Feature

#194 [refactor] 필터에 검색 기능 추가
  server/src/main/java/com/moovda_project/moovda/global/exception/ExceptionCode.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/search/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
  server/src/main/java/com/moovda_project/moovda/module/watch/repository/WatchedRepository.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/ToWatchService.java
Labels: Feature, Refactor

#151 [feat] auth, 헤더 풋터 css 수정
  client/src/app/(membership)/login/page.styled.ts
  client/src/app/(membership)/login/page.tsx
  client/src/app/api/auth/[...nextauth]/route.ts
  client/src/app/search/page.tsx
  client/src/components/Footer/Footer.styled.ts
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.styled.ts
  client/src/components/Header/Header.tsx
  client/src/redux/features/authSlice.ts
  client/src/redux/features/loginSlice.ts
  client/src/redux/store.ts
  client/src/styles/Globalstyle.tsx
Labels: Documentation

#197 [Feat] JWT에서 memberId 추출
  client/package-lock.json
  client/package.json
  client/src/app/(membership)/login/page.tsx
  client/src/app/(membership)/mypage/[memberId]/page.tsx
  client/src/components/Header/Header.styled.ts
  client/src/components/Header/Header.tsx
  client/src/redux/features/authSlice.ts
Labels: Feature

#200 [feat] 영화 상세 페이지 구현
  client/src/api/axiosHandler.ts
  client/src/app/(membership)/mypage/[memberId]/dummydata.ts
  client/src/app/(membership)/mypage/[memberId]/page.styled.ts
  client/src/app/(membership)/mypage/[memberId]/page.tsx
  client/src/app/movie/page.tsx
  client/src/app/movies/[movieId]/dummydata.ts
  client/src/app/movies/[movieId]/page.styled.ts
  client/src/app/movies/[movieId]/page.tsx
  client/src/app/page.tsx
  client/src/assets/StarHalfLeft.svg
  client/src/assets/StarHalfRight.svg
  client/src/assets/close.svg
  client/src/assets/emptyStar.svg
  client/src/assets/faStarHalf.svg
  client/src/assets/heart.svg
  client/src/assets/penIcon.svg
  client/src/assets/plus.svg
  client/src/components/CommentBox/Comment.styled.ts
  client/src/components/CommentBox/Comment.tsx
  client/src/components/CommentModal/Modal.styled.ts
  client/src/components/CommentModal/Modal.tsx
  client/src/components/MainCarousel/MainCarousel.tsx
  client/src/components/MainPoster/MainPoster.tsx
  client/src/components/MyCarousel/MyCarousel.styled.ts
  client/src/components/MyCarousel/MyCarousel.tsx
  client/src/components/StaffBox/StaffBox.styled.ts
  client/src/components/StaffBox/StaffBox.tsx
  client/src/components/Starrate/StarrateShow.tsx
  client/src/redux/features/commentSlice.ts
  client/src/redux/features/starSlice.ts
  client/src/redux/store.ts
Labels: Feature

#204 [refactor] Comment, Movie 리팩토링
  server/src/main/java/com/moovda_project/moovda/global/dto/PageDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPatchDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentPostDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/comment/mapper/CommentMapper.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/like/entity/Like.java
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/api/MovieApiService.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieMainResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/PagedMovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/genre/GenreResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/search/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/staff/StaffResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/genre/Genre.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/staff/Staff.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/module/watch/dto/ToWatchResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/watch/dto/WatchedResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/ToWatch.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/Watched.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/ToWatchService.java
Labels: Refactor

#206 [refactor] 패키지 구조 수정
  server/src/main/java/com/moovda_project/moovda/module/genre/entity/Genre.java
  server/src/main/java/com/moovda_project/moovda/module/genre/entity/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/module/genre/repository/GenreRepository.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/entity/Movie.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieApiService.java
  server/src/main/java/com/moovda_project/moovda/module/staff/entity/MovieStaff.java
  server/src/main/java/com/moovda_project/moovda/module/staff/entity/Staff.java
  server/src/main/java/com/moovda_project/moovda/module/staff/repository/StaffRepository.java
Labels: Refactor

#207 [feat] Question 조회 시 답변 수 표시
  server/src/main/java/com/moovda_project/moovda/module/answer/service/AnswerService.java
Labels: Feature

#210 [refactor] 테이블명 수정
  server/src/main/java/com/moovda_project/moovda/module/answer/entity/Answer.java
  server/src/main/java/com/moovda_project/moovda/module/answer/service/AnswerService.java
  server/src/main/java/com/moovda_project/moovda/module/genre/entity/MovieGenre.java
Labels: Refactor

#212 [fix] filter 에러 해결
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/search/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
Labels: Fix

#213 [feat] Question 조회 시 답변 수 표시
  server/src/main/java/com/moovda_project/moovda/module/question/entity/Question.java
Labels: Feature

#215 [Feat] Searchpage 기능구현
  client/.gitignore
  client/src/app/(membership)/login/page.tsx
  client/src/app/search/page.styled.ts
  client/src/app/search/page.tsx
  client/src/components/Filter/NavigationBar.styled.ts
  client/src/components/Filter/NavigationBar.tsx
  client/src/components/Filter/Pagination.styled.ts
  client/src/components/Filter/Pagination.tsx
Labels: Feature, Fix

#216 [feat] search modal
  client/src/components/Question/Modal.tsx
  client/src/components/Question/SearchBox.styled.ts
  client/src/components/Question/SearchBox.tsx
Labels: Feature

#217 [feat] 서버 주소 연결
  client/src/app/(membership)/mypage/[memberId]/page.tsx
  client/src/app/movies/[movieId]/page.tsx
  client/src/app/page.tsx
  client/src/components/CommentBox/Comment.tsx
  client/src/components/CommentModal/Modal.tsx
Labels: Feature

#218 [feat] modal component
  client/src/components/Question/Modal.styled.ts
  client/src/components/Question/Modal.tsx
Labels: Feature

#221 [refactor] 영화 데이터 추가 및 리팩토링
  server/src/main/java/com/moovda_project/moovda/module/comment/controller/CommentController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/genre/dto/GenreResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/genre/entity/MovieGenre.java
  server/src/main/java/com/moovda_project/moovda/module/like/controller/LikeController.java
  server/src/main/java/com/moovda_project/moovda/module/like/service/LikeService.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieApiController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieController.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieDataInitializer.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieSearchCondition.java
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieSearchDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryCustom.java
  server/src/main/java/com/moovda_project/moovda/module/movie/repository/MovieRepositoryImpl.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
  server/src/main/java/com/moovda_project/moovda/module/staff/dto/StaffResponseDto.java
Labels: Refactor

#219 [feat] answerbox component
  client/src/components/Question/AnswerBox.tsx
  client/src/redux/features/answerListSlice.ts
  client/src/redux/store.ts
Labels: Feature

#222 [feat] questionbox 기능구현
  client/src/components/Question/QuestionBox.tsx
Labels: Feature

#223 [feat] question-create-page
  client/src/app/questions/create/page.tsx
Labels: Feature

#224 [feat] question detail page
  client/src/app/questions/[questionId]/page.styled.ts
  client/src/app/questions/[questionId]/page.tsx
Labels: Feature

#225 [feat] question list page
  client/src/app/questions/page.styled.ts
  client/src/app/questions/page.tsx
Labels: Feature

#227 [fix] yml 파일 수정
  server/src/main/resources/application.yml
Labels: Fix

#230 [feat] Question 수정
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
  server/src/main/java/com/moovda_project/moovda/module/question/service/QuestionService.java
Labels: Feature, Refactor

#236 [fix] 코멘트 삭제 에러 수정
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
Labels: Fix

#233 [refactor] 상세 질문 조회 Controller 수정
  server/src/main/java/com/moovda_project/moovda/module/question/controller/QuestionController.java
Labels: Refactor

#238 [feat] HealthCheckController 추가
  server/src/main/java/com/moovda_project/moovda/global/utils/HealthCheckController.java
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/comment/entity/Comment.java
  server/src/main/java/com/moovda_project/moovda/module/like/repository/LikeRepository.java
Labels: Feature

#237 [feat] 답변에 영화 등록 추가
  server/src/main/java/com/moovda_project/moovda/module/answer/dto/AnswerDto.java
  server/src/main/java/com/moovda_project/moovda/module/answer/service/AnswerService.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Feature

#245 [refactor] Answer entity title,poster 추가
  server/src/main/java/com/moovda_project/moovda/module/answer/entity/Answer.java
Labels: Refactor

#246 [refactor] 질문 답변 테스트 오류 수정
  server/src/main/java/com/moovda_project/moovda/module/answer/controller/AnswerController.java
  server/src/main/java/com/moovda_project/moovda/module/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Refactor

#248 [refactor] 질문 조회 시 movie 수정
  server/src/main/java/com/moovda_project/moovda/module/answer/dto/AnswerDto.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Refactor

#251 [feat] 질문 상세 조회 시 answers에 대한 pageInfo 추가
  server/src/main/java/com/moovda_project/moovda/module/question/dto/QuestionDto.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Feature

#252 [fix] Unmapped target properties
  server/src/main/java/com/moovda_project/moovda/module/answer/mapper/AnswerMapper.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Fix

#258 [feat] oauth 로그인
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/moovda_project/moovda/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/JwtLogoutSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/moovda_project/moovda/global/auth/service/CustomOAuth2UserService.java
  server/src/main/java/com/moovda_project/moovda/global/auth/service/TokenBlacklistService.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/MemberDetailsImpl.java
  server/src/main/java/com/moovda_project/moovda/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/member/repository/MemberRepository.java
  server/src/main/java/com/moovda_project/moovda/module/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: Feature

#262 [feat] oauth 설정2
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
Labels: Feature

#263 [refactor] nickname 추가
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Refactor

#264 [refactor] nickname 추가
  server/src/main/java/com/moovda_project/moovda/module/comment/dto/CommentResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
Labels: Refactor

#265 [refactor] openingDate 추가
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieService.java
Labels: Refactor

#269 [refactor] Answers에 prodYear 추가
  server/src/main/java/com/moovda_project/moovda/module/answer/dto/AnswerDto.java
  server/src/main/java/com/moovda_project/moovda/module/answer/entity/Answer.java
  server/src/main/java/com/moovda_project/moovda/module/question/mapper/QuestionMapper.java
Labels: Refactor

#270 [fix] cors 에러 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfiguration.java
Labels: Fix

#271 [fix] nickname 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/service/CustomOAuth2UserService.java
  server/src/main/java/com/moovda_project/moovda/module/member/dto/MemberResponseDto.java
Labels: Fix

#272 [refactor] OAuth2 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Refactor

#273 [fix] redirect uri 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Fix

#274 [fix] redirect uri 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Fix

#276 [feat] oauth 설정3
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/resources/application.yml
Labels: Feature

#277 [fix] redirect_uri 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Fix

#278 [fix] redirect_uri 수정
  server/src/main/resources/application.yml
Labels: Fix

#279 Feat/minwoo/oauth4
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Feature

#280 [feat] oauth 설정4
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/resources/application.yml
Labels: Feature

#282 [feat] oauth 설정4
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Feature

#284 [Deploy] 배포
  .DS_Store
  client/next.config.js
  client/package.json
  client/src/app/(membership)/login/page.styled.ts
  client/src/app/(membership)/login/page.tsx
  client/src/app/_app.tsx
  client/src/app/_document.js
  client/src/app/api/auth/[...nextauth]/route.ts
  client/src/app/layout.tsx
  client/src/app/search/page.tsx
  client/src/components/Filter/NavigationBar.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Token/GoogleLoginToken.tsx
  client/src/redux/features/authSlice.ts
Labels: Deployment

#286 [feat] oauth 설정4
  server/src/main/java/com/moovda_project/moovda/global/auth/config/SecurityConfiguration.java
Labels: Feature

#287 [feat] oauth 설정4
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Fix

#288 [fix] Access Token 키 값 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Fix

#290 [fix] Redirect URI 변경
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Fix

#291 [feat] oauth 수정
  server/src/main/java/com/moovda_project/moovda/global/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Feature

#292 [fix] 오류 수정
  client/src/app/questions/[questionId]/page.tsx
  client/src/app/questions/create/page.tsx
  client/src/app/questions/edit/[questionId]/page.tsx
  client/src/app/questions/page.tsx
  client/src/components/Question/AnswerBox.tsx
  client/src/components/Question/Modal.styled.ts
  client/src/components/Question/Modal.tsx
  client/src/components/Question/SearchBox.tsx
Labels: Fix

#297 [fix] fix3
  client/src/app/questions/[questionId]/page.styled.ts
  client/src/app/questions/[questionId]/page.tsx
  client/src/components/Question/AnswerBox.styled.ts
  client/src/components/Question/AnswerBox.tsx
  client/src/components/Question/SearchBox.styled.ts
Labels: Fix

#302 [fix] Response 이름 변경
  server/src/main/java/com/moovda_project/moovda/module/movie/dto/MovieFilterResponseDto.java
  server/src/main/java/com/moovda_project/moovda/module/movie/mapper/MovieMapper.java
Labels: Fix

#303 Fix/soobin/fix4
  client/src/components/Header/Header.tsx
  client/src/redux/features/loginSlice.ts
  client/src/redux/features/userinfoSlice.ts
  client/src/redux/store.ts
Labels: Feature, Fix

#305 [fix] Builder.default 추가
  server/src/main/java/com/moovda_project/moovda/module/member/entity/Member.java
Labels: Fix

#307 [fix] 무비 데이터 추가
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieApiController.java
Labels: Fix

#309 [fix] watched 에러 수정
  server/src/main/java/com/moovda_project/moovda/module/comment/service/CommentService.java
  server/src/main/java/com/moovda_project/moovda/module/member/mapper/MemberMapper.java
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieApiController.java
  server/src/main/java/com/moovda_project/moovda/module/watch/entity/Watched.java
  server/src/main/java/com/moovda_project/moovda/module/watch/service/WatchedService.java
Labels: Fix

#310 [fix] 영화 데이터 추가
  server/src/main/java/com/moovda_project/moovda/module/movie/controller/MovieApiController.java
Labels: Fix

#313 [fix] memberId, questionId 수정 (#21)
  client/src/components/Question/AnswerBox.tsx
  client/src/redux/features/answerListSlice.ts
Labels: Fix

#315 [fix] posterURL 수정
  server/src/main/java/com/moovda_project/moovda/module/movie/service/MovieApiService.java
Labels: Fix

#321 [refactor] AnswerDto prodYear 추가
  server/src/main/java/com/moovda_project/moovda/module/answer/dto/AnswerDto.java
Labels: Refactor

#324 [refactor] AnswerService prodYear 추가
  server/src/main/java/com/moovda_project/moovda/module/answer/service/AnswerService.java
Labels: Refactor

#325 [fix] poster 이미지 수정 (#21)
  client/src/components/Question/AnswerBox.styled.ts
  client/src/components/Question/AnswerBox.tsx
Labels: Fix

#328 [fix] 이미지 크기 수정 (#21)
  client/src/components/Question/AnswerBox.tsx
Labels: Fix

#329 [feat] delete member
  server/src/main/java/com/moovda_project/moovda/module/member/controller/MemberController.java
  server/src/main/java/com/moovda_project/moovda/module/member/service/MemberService.java
Labels: Feature

#333 [fix] 디자인, axios 오류 수정
  client/src/app/questions/[questionId]/page.styled.ts
  client/src/app/questions/[questionId]/page.tsx
  client/src/app/questions/page.tsx
  client/src/components/Question/AnswerBox.styled.ts
  client/src/components/Question/AnswerBox.tsx
  client/src/components/Question/Modal.styled.ts
  client/src/components/Question/Modal.tsx
  client/src/components/Question/SearchBox.styled.ts
  client/src/components/Question/SearchBox.tsx
Labels: Fix

#335 Fix/yh/fix4
  client/src/app/questions/[questionId]/page.tsx
  client/src/components/Question/AnswerBox.styled.ts
  client/src/components/Question/AnswerBox.tsx
Labels: Fix

#336 [fix] 현재 시간 수정
  client/src/app/questions/[questionId]/page.tsx
  client/src/components/Question/AnswerBox.tsx
Labels: Fix
